version: '2'

services:
  mongodb:
    image: mongo

  api:
    build: .
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://mongodb/canvasrun
    volumes:
      - .:/api
      - /api/node_modules
    depends_on:
      - mongodb
    links:
      - mongodb

  ui:
    build:
      context: ./client
    environment:
      NODE_ENV: development
    ports:
      - "6543:6543"
    volumes:
      - .:/ui
      - /ui/node_modules
    depends_on:
      - api
    links:
      - api
